version: 1.0
publish: app
services:
  app:
    command: npm run start
    environment:
      TEST: blaat
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 8080
        public: 80
